steps:
  - label: "Detect changed projects"
    key: diff
    soft_fail: true
    env:
      BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: "true"
    plugins:
      - j1mr10rd4n/monorepo-diff#v1.11.3:
          diff: .buildkite/scripts/git-diff-files.sh
          watch:
            - path: "service-app"
              config:
                label: "monorepo-service-app"
                command: "buildkite-agent pipeline upload serivce-app/.buildkite/pipeline.yml"
                label: "Upload monorepo service-app pipeline"
                key: service-app-pipeline-upload
            - path: "test"
              config:
                label: "monorepo-test"
                command: "buildkite-agent pipeline upload test/.buildkite/pipeline.yml"
                label: "Upload monorepo test pipeline"
                key: test-pipeline-upload
          log_level: "debug"
